### ISSUE TITLE
Validar quando um CRD usa uma version que não existe

### ISSUE THREAD

**Issue by daltonmatos** [lukerops/manifest.tf#20]
Exemplo de CRD:
```yaml
apiVersion: tf-gapi.lukerops.com/v1alpha3
kind: CustomResourceDefinition
metadata:
  name: user.gcp.iam
spec:
  group: gcp.iam
  kind: User
  versions:
    - name: v1alpha2
      specSchema:
        type: object
        properties:
          email:
            type: string
          active:
            type: bool
            default: false
```

Se a verĩon `v1alpha3` não existe no manifest.tf um erro não amigável é mostrado.
![Captura de tela de 2024-10-11 08-57-31](https://github.com/user-attachments/assets/94bd80f9-b488-4def-8c37-aa24eb4bc01d)

Poderíamos validar e mostrar um erro amigável explicando o que aconteceu.
