### ISSUE TITLE
Proposta de novo tipo de campo: Enum

### ISSUE THREAD

**Issue by daltonmatos** [lukerops/manifest.tf#26]
Poderíamos pensar em um tipo de campo novo, além dos que já temos (integer, bool, string, array, object). Seria um tipo simples mas com um conjunto fechado de valores possíveis.

Proposta de CRD com esse novo campo:
```yaml
apiVersion: manifest-tf.lukerops.com/v1alpha3
kind: CustomResourceDefinition
metadata: 
  name: user.iam.cloud
spec:
  group: iam.cloud
  kind: User
  versions:
    - name: v1alpha1
      specSchema:
        type: object
        properties:
          name:
            type: string
          kind:
            type: enum
            values: 
              - Group
              - ServiceAccount
              - Topic
              - User
            default: User
```
E um manifesto de exemplo para esse CRD:

```yaml
apiVersion: iam.cloud/v1alpha1
kind: User
metadata:
  name: user-teste
spec:
  name: User One
  kind: Topic
```
E um manifesto que faz uso da funcionalidade de valor default (#16):
```yaml
apiVersion: iam.cloud/v1alpha1
kind: User
metadata:
  name: user-teste
spec:
  name: User One
```
(Esse novo tipo já nascerá com suporte a default value)

# Validações
- O campo do tipo enum só pode ter seu valor com uma das opções definidas no CRD.
- Não devemos permitir um valor default diferente das opções que o enum propõe. Por exemplo não podemos permitir que o valor default de um campo desse seja `""`, pois isso violaria a garantia de sempre termos um dos valores possíveis como o valor do campo.

# Dúvidas:
- Seria sempre um campo com valores string?
- Faz sentido termos um enum onde os valores possíveis são, por exemplo: 1, 2, 3, 4
    - Se sim. Como esses valores seriam entregues no output final do manifest.tf? Como inteiros? Como strings?
